### ISSUE TITLE
create form for generating a secure password

### ISSUE THREAD

**Issue by LiamTownsley2** [CMP315/Desktop-App#13]

**Comment by sims438** [comment]
hi can i take this?

**Comment by LiamTownsley2** [comment]
sure, for just now probably best just to create a new form in the app and create it like that, once we have the main screen working then it'll be easier for us to add in an option to generate it when you go to create it (like other password managers do)

**Comment by sims438** [comment]
okay noted.I'll start working on it now

**Comment by LiamTownsley2** [comment]
any update? @sims438

**Comment by LiamTownsley2** [comment]
Partially implemented in Create & Edit passwords page.
You can still create the one one its own dedicated form as this one should hopefully allow the user to decide what characters they would like inside the password and how long it should be.
![3wQUyVS](https://github.com/CMP315/Desktop-App/assets/88986614/882780da-bd2b-46ae-b344-0a195235a3e8)

**Comment by sims438** [comment]
Hi,sorry for the delay something unexpected came up and had a busy week.I see you completed this one, Is there anything else i can help with?

**Comment by LiamTownsley2** [comment]
just wondering haha are you in CMP315 or did you just find the repo via
github?

**Comment by sims438** [comment]
No lmao i just found out via github randomly

**Comment by LiamTownsley2** [comment]
hahaha can’t merge any commits you make its uni work 😂😂 apologies my
friend
